# Generated by Django 4.2.8 on 2026-03-28 00:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChuyenXe',
            fields=[
                ('ChuyenXeID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('NgayKhoiHanh', models.DateTimeField()),
                ('GioDi', models.DateTimeField(blank=True, null=True)),
                ('GioDen', models.DateTimeField(blank=True, null=True)),
                ('TrangThai', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'ChuyenXe',
            },
        ),
        migrations.CreateModel(
            name='GheNgoi',
            fields=[
                ('GheID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('SoGhe', models.CharField(max_length=5)),
                ('TrangThai', models.CharField(blank=True, max_length=20, null=True)),
                ('ChuyenXeID', models.ForeignKey(blank=True, db_column='ChuyenXeID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='nhaxe.chuyenxe')),
            ],
            options={
                'db_table': 'GheNgoi',
            },
        ),
        migrations.CreateModel(
            name='KhachHang',
            fields=[
                ('KhachHangID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('HoTen', models.CharField(max_length=200)),
                ('Email', models.CharField(blank=True, max_length=100, null=True)),
                ('NgayDangKy', models.DateTimeField(blank=True, null=True)),
                ('AnhDaiDienURL', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'KhachHang',
            },
        ),
        migrations.CreateModel(
            name='NhaXe',
            fields=[
                ('NhaxeID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Hoten', models.CharField(max_length=200)),
                ('Email', models.CharField(max_length=100)),
                ('NgayDangKy', models.DateTimeField(blank=True, null=True)),
                ('AnhDaiDienURL', models.CharField(blank=True, max_length=100, null=True)),
                ('DiaChiTruSo', models.CharField(blank=True, max_length=200, null=True)),
                ('SoDienThoai', models.CharField(max_length=12, unique=True)),
            ],
            options={
                'db_table': 'NhaXe',
            },
        ),
        migrations.CreateModel(
            name='Xe',
            fields=[
                ('XeID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('BienSoXe', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('TrangThai', models.CharField(blank=True, max_length=20, null=True)),
                ('SoGhe', models.CharField(blank=True, max_length=10, null=True)),
                ('NhaxeID', models.ForeignKey(blank=True, db_column='NhaxeID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='nhaxe.nhaxe')),
            ],
            options={
                'db_table': 'Xe',
            },
        ),
        migrations.CreateModel(
            name='Ve',
            fields=[
                ('VeID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('TenHanhKhach', models.CharField(max_length=200)),
                ('SoDienThoai', models.CharField(blank=True, max_length=10, null=True)),
                ('NgayDat', models.DateTimeField(blank=True, null=True)),
                ('GiaVe', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('TrangThaiThanhToan', models.CharField(blank=True, max_length=20, null=True)),
                ('DiemDon', models.CharField(blank=True, max_length=150, null=True)),
                ('DiemTra', models.CharField(blank=True, max_length=150, null=True)),
                ('ChuyenXeID', models.ForeignKey(blank=True, db_column='ChuyenXeID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='nhaxe.chuyenxe')),
                ('GheID', models.ForeignKey(blank=True, db_column='GheID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='nhaxe.ghengoi')),
                ('KhachHangID', models.ForeignKey(blank=True, db_column='KhachHangID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='nhaxe.khachhang')),
            ],
            options={
                'db_table': 'Ve',
            },
        ),
        migrations.CreateModel(
            name='TuyenXe',
            fields=[
                ('TuyenXeID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('TenTuyen', models.CharField(max_length=500)),
                ('DiemDi', models.CharField(max_length=500)),
                ('DiemDen', models.CharField(max_length=500)),
                ('QuangDuong', models.CharField(blank=True, max_length=500, null=True)),
                ('DiemTrungGian', models.CharField(blank=True, max_length=500, null=True)),
                ('NhaxeID', models.ForeignKey(db_column='NhaxeID', on_delete=django.db.models.deletion.CASCADE, to='nhaxe.nhaxe')),
            ],
            options={
                'db_table': 'TuyenXe',
            },
        ),
        migrations.CreateModel(
            name='ThanhToan',
            fields=[
                ('ThanhToanID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('SoTien', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('PhuongThucTT', models.CharField(blank=True, max_length=20, null=True)),
                ('TrangThaiThanhToan', models.CharField(blank=True, max_length=20, null=True)),
                ('NgayThanhToan', models.DateTimeField(blank=True, null=True)),
                ('MaGiaoDich', models.CharField(blank=True, max_length=10, null=True)),
                ('VeID', models.ForeignKey(blank=True, db_column='VeID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='nhaxe.ve')),
            ],
            options={
                'db_table': 'ThanhToan',
            },
        ),
        migrations.CreateModel(
            name='TaiXe',
            fields=[
                ('TaixeID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('HoTen', models.CharField(max_length=200)),
                ('SoCCCD', models.CharField(blank=True, max_length=12, null=True)),
                ('LoaiBangLai', models.CharField(blank=True, max_length=20, null=True)),
                ('NgayHetHanBangLai', models.DateTimeField(blank=True, null=True)),
                ('HinhAnhURL', models.CharField(blank=True, max_length=100, null=True)),
                ('SoBangLai', models.CharField(blank=True, max_length=20, null=True)),
                ('NhaxeID', models.ForeignKey(db_column='NhaxeID', on_delete=django.db.models.deletion.CASCADE, to='nhaxe.nhaxe')),
            ],
            options={
                'db_table': 'TaiXe',
            },
        ),
        migrations.CreateModel(
            name='LoaiXe',
            fields=[
                ('LoaiXeID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('TenLoaiXe', models.CharField(max_length=50)),
                ('SoCho', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('SoDoGheNgoiURL', models.CharField(blank=True, max_length=100, null=True)),
                ('GiaVe', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('NgayCapNhatGia', models.DateField(blank=True, null=True)),
                ('NhaxeID', models.ForeignKey(blank=True, db_column='NhaxeID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='nhaxe.nhaxe')),
            ],
            options={
                'db_table': 'LoaiXe',
            },
        ),
        migrations.AddField(
            model_name='ghengoi',
            name='XeID',
            field=models.ForeignKey(blank=True, db_column='XeID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='nhaxe.xe'),
        ),
        migrations.CreateModel(
            name='DanhGia',
            fields=[
                ('DanhGiaID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('DiemSo', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('NhanXet', models.CharField(blank=True, max_length=500, null=True)),
                ('NgayDanhGia', models.DateTimeField(blank=True, null=True)),
                ('KhachHangID', models.ForeignKey(blank=True, db_column='KhachHangID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='nhaxe.khachhang')),
                ('VeID', models.ForeignKey(blank=True, db_column='VeID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='nhaxe.ve')),
            ],
            options={
                'db_table': 'DanhGia',
            },
        ),
        migrations.AddField(
            model_name='chuyenxe',
            name='TaixeID',
            field=models.ForeignKey(blank=True, db_column='TaixeID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='nhaxe.taixe'),
        ),
        migrations.AddField(
            model_name='chuyenxe',
            name='TuyenXeID',
            field=models.ForeignKey(blank=True, db_column='TuyenXeID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='nhaxe.tuyenxe'),
        ),
        migrations.AddField(
            model_name='chuyenxe',
            name='XeID',
            field=models.ForeignKey(blank=True, db_column='XeID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='nhaxe.xe'),
        ),
    ]
