# Generated by Django 4.2.8 on 2026-04-10 08:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nhaxe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Authentication',
            fields=[
                ('UserID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('TenDangNhap', models.CharField(max_length=200, unique=True)),
                ('MatKhau', models.CharField(max_length=200)),
                ('Vaitro', models.CharField(max_length=20)),
                ('SoDienThoai', models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='Số điện thoại phải bắt đầu bằng 0 và có ít nhất 10 số', regex='^0\\d{9,}$')])),
                ('KhachHang', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nhaxe.khachhang')),
                ('Nhaxe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nhaxe.nhaxe')),
            ],
        ),
    ]
