# Generated by Django 4.2.8 on 2026-04-10 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nhaxe', '0002_user_authentication'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_Authentication',
        ),
    ]
