# Generated by Django 6.0.4 on 2026-04-13 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhaxe', '0003_delete_user_authentication'),
    ]

    operations = [
        migrations.AddField(
            model_name='xe',
            name='HinhAnhXe',
            field=models.ImageField(blank=True, null=True, upload_to='xe/'),
        ),
        migrations.AlterField(
            model_name='loaixe',
            name='GiaVe',
            field=models.DecimalField(decimal_places=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='loaixe',
            name='LoaixeID',
            field=models.CharField(blank=True, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='loaixe',
            name='NgayCapNhatGia',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='xe',
            name='TrangThai',
            field=models.CharField(default='Đang hoạt động', max_length=50),
        ),
        migrations.AlterField(
            model_name='xe',
            name='XeID',
            field=models.CharField(blank=True, max_length=10, primary_key=True, serialize=False),
        ),
    ]
