# Generated by Django 6.0.3 on 2026-04-13 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhaxe', '0004_xe_hinhanhxe_alter_loaixe_giave_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nhaxe',
            name='AnhDaiDienURL',
        ),
        migrations.AddField(
            model_name='nhaxe',
            name='AnhDaiDien',
            field=models.ImageField(blank=True, null=True, upload_to='nhaxe/'),
        ),
    ]
