# Generated by Django 6.0.4 on 2026-04-17 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhaxe', '0005_remove_nhaxe_anhdaidienurl_nhaxe_anhdaidien'),
    ]

    operations = [
        migrations.AddField(
            model_name='taixe',
            name='HovaTen',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='chuyenxe',
            name='TrangThai',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
