# Generated by Django 6.0.1 on 2026-04-17 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhaxe', '0005_remove_nhaxe_anhdaidienurl_nhaxe_anhdaidien'),
    ]

    operations = [
        migrations.AddField(
            model_name='taixe',
            name='HoTen',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
