# Generated by Django 6.0.1 on 2026-04-17 16:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhaxe', '0006_taixe_hoten'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taixe',
            name='NgayHetHanBangLai',
        ),
        migrations.AlterField(
            model_name='taixe',
            name='LoaiBangLai',
            field=models.CharField(blank=True, choices=[('B1', 'B1'), ('B', 'B'), ('C', 'C'), ('C1', 'C1')], default='B1', max_length=2, null=True),
        ),
        migrations.CreateModel(
            name='User_Authentication',
            fields=[
                ('UserID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('TenDangNhap', models.CharField(max_length=200, unique=True)),
                ('MatKhau', models.CharField(max_length=200)),
                ('Vaitro', models.CharField(max_length=20)),
                ('SoDienThoai', models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='Số điện thoại phải bắt đầu bằng 0 và có ít nhất 10 số', regex='^0\\d{9,}$')])),
                ('KhachHang', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nhaxe.khachhang')),
                ('Nhaxe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nhaxe.nhaxe')),
            ],
        ),
    ]
