# Generated by Django 4.2.8 on 2026-04-17 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nhaxe', '0008_user_authentication_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_authentication',
            name='Taixe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nhaxe.taixe'),
        ),
    ]
