# Generated by Django 6.0.1 on 2026-04-17 14:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhaxe', '0009_user_authentication_taixe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='danhgia',
            name='Ve',
        ),
        migrations.RemoveField(
            model_name='nhaxe',
            name='AnhDaiDien',
        ),
        migrations.RemoveField(
            model_name='taixe',
            name='HovaTen',
        ),
        migrations.RemoveField(
            model_name='user_authentication',
            name='Taixe',
        ),
        migrations.RemoveField(
            model_name='xe',
            name='HinhAnhXe',
        ),
        migrations.AddField(
            model_name='danhgia',
            name='Nhaxe',
            field=models.ForeignKey(default='NX00001', on_delete=django.db.models.deletion.CASCADE, to='nhaxe.nhaxe'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nhaxe',
            name='AnhDaiDienURL',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='nhaxe',
            name='SoLuotDanhGia',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='nhaxe',
            name='TongDiemDanhGia',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='danhgia',
            name='NgayDanhGia',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='danhgia',
            name='Nhanxet',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='khachhang',
            name='Email',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='loaixe',
            name='LoaixeID',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='loaixe',
            name='NgayCapNhatGia',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nhaxe',
            name='DiaChiTruSo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='nhaxe',
            name='Email',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='nhaxe',
            name='SoDienThoai',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='SĐT nhà xe phải có từ 10-12 chữ số', regex='^\\d{10,12}$')]),
        ),
        migrations.AlterField(
            model_name='thanhtoan',
            name='NgayThanhToan',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='thanhtoan',
            name='SoTien',
            field=models.DecimalField(decimal_places=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='tuyenxe',
            name='QuangDuong',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_authentication',
            name='SoDienThoai',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='SĐT phải từ 10-12 số', regex='^\\d{10,12}$')]),
        ),
        migrations.AlterField(
            model_name='ve',
            name='GiaVe',
            field=models.DecimalField(decimal_places=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='ve',
            name='SoDienThoai',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='SĐT phải có từ 10-12 số', regex='^\\d{10,12}$')]),
        ),
        migrations.AlterField(
            model_name='ve',
            name='TrangThaiThanhToan',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='xe',
            name='TrangThai',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='xe',
            name='XeID',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
