# Generated by Django 6.0.1 on 2026-04-17 14:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhaxe', '0010_remove_danhgia_ve_remove_nhaxe_anhdaidien_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_authentication',
            name='SoDienThoai',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='SĐT phải từ 10-12 số', regex='^\\d{10,12}$')]),
        ),
    ]
