# Generated by Django 6.0.1 on 2026-04-17 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhaxe', '0011_alter_user_authentication_sodienthoai'),
    ]

    operations = [
        migrations.AddField(
            model_name='danhgia',
            name='AnDanh',
            field=models.BooleanField(default=False),
        ),
    ]
