# Generated by Django 6.0.1 on 2026-04-17 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhaxe', '0012_danhgia_andanh_danhgia_ve'),
    ]

    operations = [
        migrations.AddField(
            model_name='danhgia',
            name='Ve',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nhaxe.ve'),
        ),
    ]
