# Generated by Django 6.0.1 on 2026-04-17 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhaxe', '0013_danhgia_ve'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chitiettaixe',
            name='Tennhaxe',
        ),
        migrations.AddField(
            model_name='nhaxe',
            name='TenNhaXe',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
