# Generated by Django 6.0.1 on 2026-04-17 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhaxe', '0014_remove_chitiettaixe_tennhaxe_nhaxe_tennhaxe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taixe',
            name='NgayHetHanBangLai',
        ),
        migrations.AddField(
            model_name='taixe',
            name='HoTen',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='taixe',
            name='LoaiBangLai',
            field=models.CharField(blank=True, choices=[('B1', 'B1'), ('B', 'B'), ('C', 'C'), ('C1', 'C1')], default='B1', max_length=2, null=True),
        ),
    ]
