# Generated by Django 6.0.1 on 2026-04-29 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhaxe', '0014_remove_chitiettaixe_tennhaxe_nhaxe_tennhaxe'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuyenxe',
            name='ThoiGian',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
    ]
