# Generated by Django 6.0.4 on 2026-04-18 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhaxe', '0015_remove_taixe_ngayhethanbanglai_taixe_hoten_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ve',
            name='DiemDon',
            field=models.CharField(blank=True, db_column='Diemdon', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='ve',
            name='DiemTra',
            field=models.CharField(blank=True, db_column='Diemtra', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='ve',
            name='HoTen',
            field=models.CharField(blank=True, db_column='Hoten', max_length=200, null=True),
        ),
    ]
