# Generated by Django 6.0.4 on 2026-04-18 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhaxe', '0016_ve_diemdon_ve_diemtra_ve_hoten'),
    ]

    operations = [
        migrations.AddField(
            model_name='xe',
            name='HinhAnhXe',
            field=models.ImageField(blank=True, null=True, upload_to='xe_images/'),
        ),
        migrations.AlterField(
            model_name='ve',
            name='DiemDon',
            field=models.CharField(blank=True, db_column='DiemDon', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='ve',
            name='DiemTra',
            field=models.CharField(blank=True, db_column='DiemTra', max_length=500, null=True),
        ),
    ]
