# Generated by Django 6.0.1 on 2026-04-29 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhaxe', '0016_ve_diemdon_ve_diemtra_ve_hoten'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='khachhang',
            name='NgayDangKy',
        ),
        migrations.AddField(
            model_name='khachhang',
            name='HovaTen',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='khachhang',
            name='NgaySinh',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taixe',
            name='NgayHetHanBangLai',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ve',
            name='DiemDon',
            field=models.CharField(blank=True, db_column='DiemDon', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='ve',
            name='DiemTra',
            field=models.CharField(blank=True, db_column='DiemTra', max_length=500, null=True),
        ),
    ]
