# Generated by Django 4.2.8 on 2026-04-29 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nhaxe', '0017_xe_hinhanhxe_alter_ve_diemdon_alter_ve_diemtra'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='khachhang',
        #     name='NgayDangKy',
        # ),
        # migrations.AddField(
        #     model_name='khachhang',
        #     name='HovaTen',
        #     field=models.CharField(blank=True, max_length=200, null=True),
        # ),
        # migrations.AddField(
        #     model_name='khachhang',
        #     name='NgaySinh',
        #     field=models.DateField(blank=True, null=True),
        # ),
        migrations.AlterField(
            model_name='chuyenxe',
            name='Taixe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nhaxe.taixe'),
        ),
        migrations.AlterField(
            model_name='chuyenxe',
            name='TrangThai',
            field=models.CharField(blank=True, default='Chưa hoàn thành', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ghengoi',
            name='gheID',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ghengoi',
            name='soGhe',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='ghengoi',
            name='trangThai',
            field=models.CharField(default='Còn trống', max_length=20),
        ),
    ]
