# Generated by Django 6.0.1 on 2026-04-29 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhaxe', '0017_remove_khachhang_ngaydangky_khachhang_hovaten_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_authentication',
            name='Taixe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nhaxe.taixe'),
        ),
    ]
