# Generated by Django 4.2.8 on 2026-04-29 03:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nhaxe', '0018_remove_khachhang_ngaydangky_khachhang_hovaten_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='khachhang',
            name='NgayDangKy',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
