# Generated by Django 6.0.1 on 2026-04-29 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhaxe', '0018_user_authentication_taixe'),
    ]

    operations = [
        migrations.AddField(
            model_name='ve',
            name='TrangThai',
            field=models.CharField(default='Đã đặt', max_length=50),
        ),
        migrations.AlterField(
            model_name='taixe',
            name='HinhAnhURL',
            field=models.TextField(blank=True, null=True),
        ),
    ]
