# Generated by Django 4.2.8 on 2026-04-29 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhaxe', '0019_khachhang_ngaydangky'),
    ]

    operations = [
        migrations.AddField(
            model_name='khachhang',
            name='HovaTen',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='khachhang',
            name='NgaySinh',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='khachhang',
            name='AnhDaiDienURL',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nhaxe',
            name='AnhDaiDienURL',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taixe',
            name='HinhAnhURL',
            field=models.TextField(blank=True, null=True),
        ),
    ]
