# Generated by Django 6.0.1 on 2026-04-29 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nhaxe', '0015_tuyenxe_thoigian'),
        ('nhaxe', '0019_ve_trangthai_alter_taixe_hinhanhurl'),
        ('nhaxe', '0020_khachhang_hovaten_khachhang_ngaysinh_and_more'),
    ]

    operations = [
    ]
