# Generated by Django 6.0.1 on 2026-04-29 12:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhaxe', '0021_merge_20260429_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='nhaxe',
            name='MaNganHang',
            field=models.CharField(blank=True, help_text='Ví dụ: MB, VCB, ICB', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='nhaxe',
            name='SoTaiKhoan',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='nhaxe',
            name='TenChuTaiKhoan',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
