# Generated by Django 6.0.1 on 2026-04-29 15:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhaxe', '0022_khachhang_ngaydangky_nhaxe_manganhang_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nhaxe',
            name='PhanTramHoaHong',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='thanhtoan',
            name='DaQuyetToan',
            field=models.BooleanField(default=False),
        ),
    ]
