# Generated by Django 6.0.1 on 2026-04-29 16:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhaxe', '0023_khachhang_ngaydangky_nhaxe_phantramhoahong_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thanhtoan',
            name='MaGiaoDich',
        ),
        migrations.RemoveField(
            model_name='thanhtoan',
            name='PhuongThucTT',
        ),
        migrations.AlterField(
            model_name='thanhtoan',
            name='Ve',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='thanhtoan', to='nhaxe.ve'),
        ),
    ]
