# Generated by Django 6.0.1 on 2026-05-01 06:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhaxe', '0024_remove_thanhtoan_magiaodich_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NganHangAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TenChuTaiKhoan', models.CharField(max_length=200)),
                ('MaNganHang', models.CharField(max_length=50)),
                ('SoTaiKhoan', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Cấu hình Ngân hàng Admin',
                'verbose_name_plural': 'Cấu hình Ngân hàng Admin',
            },
        ),
    ]
