# Generated by Django 6.0.4 on 2026-05-01 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhaxe', '0025_nganhangadmin_khachhang_ngaydangky'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chitietloaixe',
            name='Tennhaxe',
        ),
        migrations.RemoveField(
            model_name='loaixe',
            name='GiaVe',
        ),
        migrations.RemoveField(
            model_name='loaixe',
            name='NgayCapNhatGia',
        ),
        migrations.AddField(
            model_name='chitietloaixe',
            name='GiaVe',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='chitietloaixe',
            name='NgayCapNhatGia',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='khachhang',
            name='NgayDangKy',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='nhaxe',
            name='HoTenNguoiDaiDien',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='chitiettaixe',
            name='Nhaxe',
            field=models.ForeignKey(db_column='Nhaxe_id', on_delete=django.db.models.deletion.CASCADE, to='nhaxe.nhaxe'),
        ),
        migrations.AlterField(
            model_name='ghengoi',
            name='ChuyenXe',
            field=models.ForeignKey(db_column='chuyenxe_id', on_delete=django.db.models.deletion.CASCADE, to='nhaxe.chuyenxe'),
        ),
        migrations.AlterField(
            model_name='ghengoi',
            name='gheID',
            field=models.CharField(db_column='gheid', max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ghengoi',
            name='soGhe',
            field=models.CharField(blank=True, db_column='soghe', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='ghengoi',
            name='trangThai',
            field=models.CharField(db_column='trangthai', default='Còn trống', max_length=20),
        ),
        migrations.AlterField(
            model_name='khachhang',
            name='AnhDaiDienURL',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='nhaxe',
            name='NgayDangKy',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='thanhtoan',
            name='DaQuyetToan',
            field=models.BooleanField(default=False, verbose_name='Đã quyết toán'),
        ),
        migrations.AlterField(
            model_name='thanhtoan',
            name='Ve',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='nhaxe.ve'),
        ),
        migrations.AlterField(
            model_name='tuyenxe',
            name='ThoiGian',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ve',
            name='ChuyenXe',
            field=models.ForeignKey(db_column='ChuyenXe_id', on_delete=django.db.models.deletion.CASCADE, to='nhaxe.chuyenxe'),
        ),
        migrations.AlterField(
            model_name='ve',
            name='Ghe',
            field=models.ForeignKey(db_column='Ghe_id', on_delete=django.db.models.deletion.CASCADE, to='nhaxe.ghengoi'),
        ),
        migrations.AlterField(
            model_name='ve',
            name='KhachHang',
            field=models.ForeignKey(db_column='KhachHang_id', on_delete=django.db.models.deletion.CASCADE, to='nhaxe.khachhang'),
        ),
    ]
