# Generated by Django 6.0.4 on 2026-05-02 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nhaxe', '0026_remove_chitietloaixe_tennhaxe_remove_loaixe_giave_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_authentication',
            old_name='TenDangNhap',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='user_authentication',
            old_name='MatKhau',
            new_name='password',
        ),
    ]
