# Generated by Django 6.0.4 on 2026-05-02 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhaxe', '0028_alter_user_authentication_options_and_more'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='loaixe',
        #     name='GiaVe',
        #     field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        # ),
        # migrations.AddField(
        #     model_name='loaixe',
        #     name='NgayCapNhatGia',
        #     field=models.DateField(blank=True, null=True),
        # ),
        # migrations.AddField(
        #     model_name='nhaxe',
        #     name='NguoiDaiDien',
        #     field=models.CharField(blank=True, max_length=200, null=True),
        # ),
        migrations.AlterField(
            model_name='chitiettaixe',
            name='NgayKetThuc',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='khachhang',
            name='AnhDaiDienURL',
            field=models.TextField(blank=True, null=True),
        ),
    ]
