# Generated by Django 6.0.1
from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('nhaxe', '0029_loaixe_giave_loaixe_ngaycapnhatgia_and_more'),
    ]

    operations = [
        # Nội dung đã được làm trống vì Database đã khớp với Model
    ]
